name: flutter_smart_devices_example
description: Example app for flutter_smart_devices
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_smart_devices:
    path: ../
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
